# Generated by Django 6.0 on 2025-12-25 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_seed_roles'),
    ]

    operations = [
    ]
