# Generated by Django 6.0 on 2025-12-27 10:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_user_roles_delete_userrolemapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='coordinators',
            field=models.ManyToManyField(blank=True, related_name='coordinated_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='photographers',
            field=models.ManyToManyField(blank=True, related_name='photographed_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
