# Generated by Django 6.0 on 2026-01-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_user_face_encoding'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photos_of_me_last_scanned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
